- sanitize_test.go
The `github_flavored_markdown` package has moved out from `go` repository into its own in https://github.com/shurcooL/go/issues/19#issuecomment-102574426. Update urls in tests accordingly for consistency.
I hope you don't mind this pull request. I know that this is just test data, and it doesn't need to be a valid url at all. But I thought it'd be nice to update it, just to avoid pointing to the outdated import path and possibly confusing some people into thinking that may be the canonical import path.
> Update urls in tests for consistency.

- policy.go
- sanitize_test.go
Closes #19
Added functions to Policy interface:
- AllowNoAttrs
- SkipElementsContent
to modify internal maps.
Use case:
Add some html tags that cannot have attributes without modification of policy.go default list. For example, "\<big>", "\<center>", etc. Or make attributes are optional.
Usage examples:
p.AllowNoAttrs().OnElements("big")
p.AllowAttrs("border", "cellpadding", "cellspacing").AllowNoAttrs().OnElements("table")
p.AllowNoAttrs().AllowAttrs("border", "cellpadding", "cellspacing").OnElements("table")
p.SkipElementsContent("style")
> Access to setOfElementsWithoutAttrs and setOfElementsToSkipContent

- policy.go
- sanitize.go
- sanitize_test.go
Option to add a single space in place of any tag that is removed by the
sanitization process. This allows text to be presented correctly within HTML
by not collapsing space when tags are removed.
i.e. "<foo>Hello</foo><bar>World</bar>" would sanitize as:
"HelloWorld" without this option, but as:
" Hello World " with this option.
> Resolves #33

- sanitize.go
Which also meant that if we were in a nested tag and that tag closed, we should
clear our state so that output is escaped again (and our tests pass without
change).
> #37 case tag erroneously was 'javascript' not 'script'

- policy.go
This will mean that if added in a policy, `<center>` and `<marquee>` can be used without attributes. Even though they're obsolete, the alternative would be whitelisting `<style>` or animations for our users.
> Add center and marquee to whitelist

- cmd/sanitise_html_email/main.go
- policy.go
- sanitize.go
- sanitize_test.go
The doctype is not sanitized and can not be, and this allows unsafe content to
be inserted into the output by encoding it within a doctype attribute. The only
safe way to handle this quickly is not to permit the doctype.
> Resolves #54 by removing AllowDocType functionality

- policy.go
- sanitize.go
- sanitize_test.go
Use of strings.ToLower() within the match for script or style handler for
TextToken results in unsanitized content being printed.
> Resolves #56 strings.ToLower() results in false match

- README.md
- doc.go
- policy.go
Just something I noticed when reading the README :-) If you can't
replace "it's" with "it is", then you should use "its".
> Fix two very small typos

- policy.go
- sanitize.go
- sanitize_test.go
We have the same issue at The Economist  flagged in https://github.com/microcosm-cc/bluemonday/issues/65 where we want to allow all data attributes. This is my starter for ten.
> allow data attributes

- policy.go
The `address` tag without attributes is safe. And we found in production that it was being stripped despite being present in the `AllowElements` list.
> Add address to DefaultElementsWithoutAttrs

- .travis.yml
- go.mod
- go.sum
Hello,
Please consider supporting [Go Modules], the new packaging standard that will be adopted fully in Go 1.12. Experimental support is in Go 1.11 and the new module paths are supported in Go 1.9.7+ and Go 1.10.3+ in a read-only manner for backwards compatibility with all supported versions of Go.
Because this library is still below version 2 and has few dependencies, the [`go.mod`] file is fairly simple. The only other thing that would need to be done if this PR were merged is to create a semver compatible tag (eg. `v1.0.2`) that users of this library can pin to.
Note that I set the language version go 1.9 in the mod file because 1.9.7 is the earliest version with partial support for reading the `go.mod` file. If you want to continue to support syntax and APIs from as early as 1.1, I …
> Support Go Modules

- README.md
- example_test.go
- go.mod
- go.sum
- handlers.go
- handlers_test.go
- policy.go
- sanitize.go
Let me know if anything needs adjusting or if you have any questions about this, I'll try to respond quickly.
> Add Css Styling for element attributes

- handlers.go
- handlers_test.go
Found/fixed an issue with the default handler for the Font-Family css property not working properly in cases including dashes, or spaces when not inside quotes
> Fixed issue with default handler for font-family not validating correctly

- sanitize.go
- sanitize_test.go
This fixes URL sanitization when there are more than one query parameter.
This goes deep into how `token.String()` works -- on `html.StartTagToken` tokens like `a` for example, include linkable attributes (`href` for example). 
Explicitly https://github.com/golang/net/blob/master/html/token.go#L100 `token.String()` escapes *all* `&` ampersands regardless of location. Since `&` is a valid query parameter delimiter we need to treat this case specifically.
fixes #88
> fixes URL sanitization with more than one query parameter

- sanitize.go
- sanitize_test.go
This PR fixes two issues.
The first issue is that if you have two query params with the same name, only the last param is included in the sanitized result. See the following test case for an example.
```
TestLinks: sanitize_test.go:171: test 9 failed;
input   : <a href="?q=1&q=2">
output  : <a href="?q=2" rel="nofollow">
expected: <a href="?q=1&q=2" rel="nofollow">
```
The second issue this PR fixes is that characters inside the query params are HTML encoded. Take the following query.
?json=%7B%22value%22%3A%22a%22%7D
| key | value |
| ----|------|
| json | {"value":"a"} |
**After sanitization the query becomes the following, which is a bug as the query is no longer valid JSON.:**
?json=%7B%26%2334%3Bvalue%26%2334%3B%3A%26%2334%3Ba%26%2334%3B%7D
| key | value |
| ----|------|
| json | …
> Fix href sanitization bugs

- sanitize.go
- sanitize_test.go
A regression of #56 occurred in which the use of ToLower allowed a
Cyrillic upper-case I to be sanitised to a standard ASCII i and
this would then permit SCRIPT tags to be injected.
> Resolves #111 carefully escape tag names

- sanitize.go
- sanitize_test.go
`sanitizedUrl`  may change the link `http://abc.com?d=1&a=2&a=3` to `http://abc.com?a=2&a=3&d=1`. This PR fix this and also renamed `sanitizedUrl` to `sanitizedURL`.
Will fix https://github.com/go-gitea/gitea/issues/14090
> Fix the bug that sanitizedUrl will change the order of the link

- sanitize.go
- sanitize_test.go
Although query components are often key=value pairs - there is no absolute requirement
for the keys to have values and if there is not a value then the equal sign should not
be added.
Fixes go-gitea/gitea#15349
Signed-off-by: Andrew Thornton <art27@cantab.net>
> Sanitize should not add forcibly add values to query components

- go.mod
- go.sum
Updates x/net to latest version which includes a newer version of /x/text. Older versions of x/test were susceptible to CVE-2020-28852.
https://nvd.nist.gov/vuln/detail/CVE-2020-28852
> Update x/net package to latest version

- .editorconfig
- .gitattributes
- .github/workflows/test.yml
- Makefile
* enforce CI to only allow formatted code
* add make target to check code format
* format code
> CI enforce code format

- helpers.go
- policy.go
- sanitize.go
- sanitize_test.go
WIP implementation of `RequireSandboxOnIFrame`.
Open questions:
- Should `RequireSandboxOnIFrame` internally call `p.AllowAttrs("sandbox").OnElements("iframe")`, or should we leave that to the user?
- When an input `<iframe>` does NOT have a `sandbox` attribute, the entire tag is omitted entirely. However, what we actually want to do is keep the tag and enforce a blank `sandbox=""` attribute. (Might be related to #68?)
- This implementation will not dedupe values in the input `sandbox` attribute (ex: `allow-downloads allow-downloads` -> `allow-downloads allow-downloads`). Is that something we should do?
Closes #135
> Add RequireSandboxOnIFrame

- policy.go
- sanitize_test.go
Follow up fix for https://github.com/microcosm-cc/bluemonday/pull/136.
`RequireSandboxOnIFrame` was incorrectly using the _index_ of the passed in sandbox values instead of the actual value. :/
> Fix incorrect handling of iframe SandboxValues

- css/handlers.go
- Allow RGB hexadecimal colors in multiple formats per the spec. For
example, all of the following formats are valid.
#fff
#ffffff
#ffffffff
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#rgb_colors
- Allow decimal lengths without a leading zero. For example, the all of
the following formats are valid.
.5em
0.5em
0
1em
https://developer.mozilla.org/en-US/docs/Web/CSS/length#syntax
> css: improve RGB hex color and length matching

- sanitize.go
- sanitize_test.go
- Currently the code will write self-closing tags with empty attributes to the output, even when the element isn't allowed to have empty attributes.
- Move to `break` to one outer scope to fix it.
> Don't write self-closing tag with empty attributes

- policy.go
- sanitize_test.go
`picture` was not in the list of elements that were allowed without attributes. Typically most HTML elements are not valid without an attribute except for 90 elements that have this capability, `picture` was absent from this list.
> Add picture to allowlist of elements that do not need attributes to resolve #161

- go.mod
- go.sum
- sanitize_test.go
Upgrade (to at least 0.7.0+) needed because of CVE-2022-41723
0.8.0 satisfies the original test that was changed in https://github.com/microcosm-cc/bluemonday/pull/148/files
> Upgrade golang.org/x/net to 0.8.0

- sanitize.go
- sanitize_test.go
Fixes #171 
Since I'm not sure about the origin of the rule `Add semi-colon to end to fix parsing issue`, I simply added trimming of the trailing spaces.
> Fix parsing style attribute with trailing spaces

- policy.go
- sanitize.go
- sanitize_test.go
This allows a bit more flexibility when we want to allow an unknown number of URL schemes (usually all parsable ones).
- Closes #174
> Allow custom URL schemes by matching regex

- policy.go
- sanitize.go
- sanitize_test.go
#175 introduced a potential dangerous change. If a user registers the regexp `.+` for scheme validation (as written in the comment) to allow all possible schemes, a link like `<a href="javascript:...">` is valid too. The Go regexp module does not implement negative lookaheads, so you can't write "all but xyz" (`(?!javascript|vbscript)`).
This PR moves the regexp check a little bit down to be only executed if there was no other explicit scheme registration was found. So now
```go
p.AllowURLSchemesMatching(regexp.MustCompile(`.+`))
p.AllowURLSchemeWithCustomPolicy("javascript", func(*url.URL) bool {
return false
})
```
will allow every scheme but `javascript`.
An alternative would be to drop `AllowURLSchemesMatching` again and add methods `DisallowURLSchemes` and …
> Prefer explicit rules over regexp

- policy.go
- sanitize.go
- sanitize_test.go
Allows for people to rewrite src tags.
Useful to proxify request and anonymize a client's data for example. (How gmail rewrites them)
> Added src rewriter

- go.mod
https://github.com/microcosm-cc/bluemonday/commit/a50ca5f2e53d33247f60655e1ed76803fc61d26d updated `go.mod` to specify the minimum Go version to be Go 1.21. This is not necessary (the module compiles with earlier versions of Go) and has the unwanted side-effect of setting the minimum version of Go to 1.21 for all projects that depend on this module, directly or indirectly.
Since Go 1.21 is not actually required, this PR reverts the minimum Go version to 1.19.
> Revert dependency on Go 1.21

- css/handlers.go
- sanitize_test.go
Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/hex-color
> #RGB        // The three-value syntax
#RGBA       // The four-value syntax
#RRGGBB     // The six-value syntax
#RRGGBBAA   // The eight-value syntax
> Support four-value syntax for CSS hex color
